// <auto-generated />
using System;
using HomeChallenge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeChallenge.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201127145228_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeChallenge.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("Client");

                    b.Property<int>("Currency");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<string>("Description");

                    b.Property<int>("ExchangeRate");

                    b.Property<DateTime>("InvoiceDate");

                    b.Property<string>("OrderId");

                    b.Property<string>("SaleAgent");

                    b.Property<DateTime>("SettleDate");

                    b.Property<int>("Vat");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
